package:
    type:           project
    name:           dotfiles
    title:          Sol's dotfiles
    keywords:       sol, home, dotfiles
    description:    |
        I use [rehome](https://github.com/hiqdev/rehome) to setup and maintain my home.

        Other tools I use:

        - [hidev](https://github.com/hiqdev/hidev) to create and maintain packages
        - [rewatcher](https://github.com/hiqdev/rewatcher) to watch changed repos

plugins:
    hiqsol/hidev-hiqsol: "<2.0"
